---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled # or :enabled or :disabled

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[ssh::default]
    attributes:
