---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[web::default]
    attributes:
